language: python
python:
  - "3.5"
before_install:
  - pip install termcolor
  - pip install coverage
  - pip install pytest pytest-cov
  - pip install coveralls
script:
  - coverage run -m unittest
after_success:
  - coveralls